### ISSUE TITLE
[Enhancement?] Export PDF do not render

### ISSUE THREAD

**Issue by emisjerry** [pistacchio/obsidian-enhanced-tables#2]
Is the export PDF redering in your roadmap?
It cannot work now.

**Comment by pistacchio** [comment]
I've never actually used the PDF rendering capabilities of Obsidian myself, so I didn't even check it out.
**Enhanced Tables** is a useful formatter, but it's mostly meant to add interactivity to tables and tables in PDFs would lose their interactivity anyway.

I'll look into it when I have time, but I wouldn't say this is a priority.

**Comment by emisjerry** [comment]
Yes, i agree. Currrently export PDF will have the following output (Using Better export PDF plugin):
The major issue will be the codeblock shown. I think i can hide it by CSS.

![image](https://github.com/pistacchio/obsidian-enhanced-tables/assets/131511/4cea244e-9d71-4e9b-8073-d44703460aa7)

**Comment by emisjerry** [comment]
I used a CSS snippet to hide the codeblock:

```css
@media print {
  .language-yaml {
    display: none;
  }
}
