### ISSUE TITLE
[Not issue] A YouTube video introducing Enhanced Tables

### ISSUE THREAD

**Issue by emisjerry** [pistacchio/obsidian-enhanced-tables#4]
Hi,

I recorded a YouTube video introducing Enhanced Tables: 
https://youtu.be/H84hDYwRWAM. 

I hope to let more Obsidian users know about it and start using it. Although the video is in Chinese, it comes with English CC subtitles.

Best regards,

Jerry

**Comment by pistacchio** [comment]
Hey, thank you! The video seems to be super professional and well done, I really appreciate you helping make the plugin well-known 😊
